# Generated by Django 5.0.2 on 2024-03-11 12:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("To Dos", "To Dos"),
                    ("In Progress", "In Progress"),
                    ("done", "done"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="added_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_added",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="added_by_username",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="itemtype",
            field=models.CharField(
                choices=[("Bug", "Bug"), ("Feature", "Feature"), ("Task", "Task")],
                default="Feature",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="last_modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_changed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="priority",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="High",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("To Dos", "To Dos"),
                    ("In Progress", "In Progress"),
                    ("done", "done"),
                ],
                default="To Dos",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="title",
            field=models.CharField(default="untitled", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
