# Generated by Django 5.0.2 on 2024-03-12 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item__status_item_added_by_item_added_by_username_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
    ]
